### ISSUE TITLE
Bug in reading/writing dumps with triclinic boxes

### ISSUE THREAD

**Issue by PhilLecl** [mphowardlab/lammpsio#46]
When reading from a dump file with a triclinic simulation box, the following error occurs:

```
File .../lammpsio/src/lammpsio/dump.py:262, in DumpFile.__iter__(self)
    260 # check for triclinic
    261 if len(box_header) == 9:
--> 262     box_tilt = [float(x) for x in box_header[6:9]]
    263 elif len(box_header) == 6:
    264     box_tilt = None

ValueError: could not convert string to float: 'pp'
```

Apparently, `lammpsio` expects a header line of the format `ITEM: BOX BOUNDS pp pp pp XY XZ YZ`, where `XY XZ YZ` are the box tilt values.
However, the actual section for a triclinic box in a LAMMPS-generated dump file looks like this:

```
ITEM: BOX BOUNDS xy xz yz xx yy zz
xlo_bound xhi_bound xy
ylo_bound yhi_bound xz
zlo_bound zhi_bound yz
```

Where the `xy xz yz` in the first line only indicates that the three tilt factors will be included on each of the three following lines ([documentation](https://docs.lammps.org/dump.html)).

The same error in formatting occurs when writing dumps using `lammpsio`.  
This is not caught by the current tests, as these only cover writing dumps with `lammpsio` and reading these same `lammsio`-written dumps back - they never actually read any dumps written by LAMMPS itself.

# LAMMPS input and dump file for reproducing

This is a short LAMMPS input for generating a dump with a triclinic box to reproduce this bug:
```
# randomly generated periodic triclinic simulation box
units real
region r1 prism -87 9 -80 58 -63 83 9 -13 5
boundary p p p
create_box 1 r1
mass * 1

# some random atoms with random velocities
create_atoms 1 random 5 20240519 NULL
velocity all create 298.15 20240519
fix thermostat all nvt temp 298.15 298.15 100.0

# dump initial coordinates
dump d1 all custom 1000 dump.test id x y z ix iy iz
run 0
```

And here's the dump generated by that input:
```
ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
5
ITEM: BOX BOUNDS xy xz yz pp pp pp
-1.0000000000000000e+02 1.8000000000000000e+01 9.0000000000000000e+00
-8.0000000000000000e+01 6.3000000000000000e+01 -1.3000000000000000e+01
-6.3000000000000000e+01 8.3000000000000000e+01 5.0000000000000000e+00
ITEM: ATOMS id x y z ix iy iz
1 -53.8 -27.0177 -49.7964 0 0 0
2 12.5084 36.216 -58.3846 0 0 0
3 -63.8617 -43.144 44.5396 0 0 0
4 -32.4514 -66.8793 -49.6918 0 0 0
5 -68.874 -30.2506 -46.2095 0 0 0
```

**Comment by mphoward** [comment]
I agree with your diagnosis of this error! I guess we have not had a research use case for a dump file with a triclinic box to catch this previously.

It is also not good that lammpsio does not actually read from / write to LAMMPS. The current tests were written 100% in lammpsio for convenience getting code coverage, but they miss cases like this where there was a mistake reading the documentation. I will open an issue to add tests similar to the one you have above for data and dump files. It shouldn't be too bad to add these tests because we can install LAMMPS with Python support from conda-forge and use that to run the LAMMPS commands we need.
